### ISSUE TITLE
关卡页面

### ISSUE THREAD

**Issue by petronny** [petronny/nonosparks#2]
这个是你在中期报告时必须要做出来的。
为了实现这个页面，需要下述知识：
1. 建立窗口，并可以指定及调整窗口大小
1. 读取json中的关卡数据
1. 使用贴图来构建棋盘，并在指定位置添加文本框
1. 在指定位置放置按钮并实现触发的功能
1. 捕捉鼠标动作，包括点击及拖动
1. 根据鼠标动作调整相应的贴图及数据
1. 检测关卡完成

最相关的java库应该是swing库

**Comment by Ljh1130marc** [comment]
一步一步来吧
